SELECT
    DISTINCT TABLE_1.CONTEST_ID,
    TABLE_1.HACKER_ID,
    TABLE_1.NAME,
    TABLE_1.SUBMISSION,
    TABLE_1.ASUBMISSION,
    TABLE_2.TVIEWS,
    TABLE_2.UVIEWS
FROM
    (
        SELECT
            CONTESTS.CONTEST_ID,
            CONTESTS.HACKER_ID,
            CONTESTS.NAME,
            SUM(SUM_SUB) OVER (
            PARTITION BY CONTESTS.CONTEST_ID) AS SUBMISSION, SUM(SUM_ASUB) OVER (PARTITION BY CONTESTS.CONTEST_ID) AS ASUBMISSION
        FROM
            CONTESTS
            INNER JOIN COLLEGES
            ON CONTESTS.CONTEST_ID = COLLEGES.CONTEST_ID
            INNER JOIN CHALLENGES
            ON COLLEGES.COLLEGE_ID = CHALLENGES.COLLEGE_ID
            INNER JOIN (
                SELECT
                    DISTINCT CHALLENGE_ID,
                    SUM(TOTAL_SUBMISSIONS) OVER (
                    PARTITION BY CHALLENGE_ID) AS SUM_SUB, SUM(TOTAL_ACCEPTED_SUBMISSIONS) OVER (PARTITION BY CHALLENGE_ID) AS SUM_ASUB
                FROM
                    SUBMISSION_STATS
            ) T2
            ON CHALLENGES.CHALLENGE_ID = T2.CHALLENGE_ID
    ) TABLE_1
    INNER JOIN (
        SELECT
            DISTINCT CONTESTS.CONTEST_ID,
            CONTESTS.HACKER_ID,
            CONTESTS.NAME,
            SUM(SUM_VIEW) OVER (
            PARTITION BY CONTESTS.CONTEST_ID) AS TVIEWS, SUM(SUM_UVIEWS) OVER (PARTITION BY CONTESTS.CONTEST_ID) AS UVIEWS
        FROM
            CONTESTS
            INNER JOIN COLLEGES
            ON CONTESTS.CONTEST_ID = COLLEGES.CONTEST_ID
            INNER JOIN CHALLENGES
            ON COLLEGES.COLLEGE_ID = CHALLENGES.COLLEGE_ID
            INNER JOIN (
                SELECT
                    DISTINCT CHALLENGE_ID,
                    SUM(TOTAL_VIEWS) OVER (
                    PARTITION BY CHALLENGE_ID) AS SUM_VIEW, SUM(TOTAL_UNIQUE_VIEWS) OVER (PARTITION BY CHALLENGE_ID) AS SUM_UVIEWS
                FROM
                    VIEW_STATS
            ) T2
            ON CHALLENGES.CHALLENGE_ID = T2.CHALLENGE_ID
    ) TABLE_2
    ON TABLE_1.CONTEST_ID = TABLE_2.CONTEST_ID
WHERE
    TABLE_1.SUBMISSION > 0
    OR TABLE_1.ASUBMISSION > 0
    OR TABLE_2.TVIEWS > 0
    OR TABLE_2.UVIEWS > 0
ORDER BY
    TABLE_1.CONTEST_ID